basePath: /memory-verse-api/v1
definitions:
  auth.CompleteProfileRequest:
    properties:
      bible_translation:
        type: string
      enable_notification:
        type: boolean
      inspiration:
        items:
          type: string
        type: array
      is_email_notification:
        type: boolean
      is_web_notification:
        type: boolean
      selected_time:
        type: string
      user_name:
        type: string
      verse_pace:
        type: string
    type: object
  auth.ForgetPasswordRequest:
    properties:
      email:
        type: string
    type: object
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  auth.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  auth.ResetPasswordRequest:
    properties:
      email:
        type: string
      new_password:
        type: string
      otp:
        type: string
    type: object
  auth.UpdateUserProfileRequest:
    properties:
      bible_translation:
        type: string
      email:
        type: string
      enable_notification:
        type: boolean
      inspiration:
        items:
          type: string
        type: array
      is_email_notification:
        type: boolean
      is_web_notification:
        type: boolean
      selected_time:
        type: string
      user_name:
        type: string
      verse_pace:
        type: string
    type: object
  memoryverse.AddToFavouriteRequest:
    properties:
      verse_id:
        type: integer
    type: object
  memoryverse.SaveUserNoteRequest:
    properties:
      content:
        type: string
      verse_reference:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      errors: {}
      message:
        type: string
      status:
        type: string
    type: object
  response.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact:
    email: ajasataiwo45@gmail.com
    name: TaiwoDev
  description: This is the Memory Verse API documentation.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Memory Verse API
  version: "1.0"
paths:
  /auth/complete-profile:
    post:
      consumes:
      - application/json
      description: Complete user's registration
      parameters:
      - description: Complete profile request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.CompleteProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Complete user profile
      tags:
      - Auth
  /auth/forget-password:
    post:
      consumes:
      - application/json
      description: Send OTP to user's email for password reset
      parameters:
      - description: Forget password request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.ForgetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Initiate password reset
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a JWT token
      parameters:
      - description: Login user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Login a user
      tags:
      - Auth
  /auth/me:
    get:
      description: Retrieve detailed information about the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user details
      tags:
      - Auth
  /auth/register-with-email:
    post:
      consumes:
      - application/json
      description: Create a new user account with email and password
      parameters:
      - description: Register user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Register a new user
      tags:
      - Auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset password using OTP sent to email
      parameters:
      - description: Reset password request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Reset user password
      tags:
      - Auth
  /auth/update-profile:
    patch:
      consumes:
      - application/json
      description: Update user's profile information
      parameters:
      - description: Update profile request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.UpdateUserProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update user profile
      tags:
      - Auth
  /auth/verify-token:
    get:
      consumes:
      - application/json
      description: Check if the provided JWT token is valid
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Verify JWT token
      tags:
      - Auth
  /memoryverse/daily-verse:
    get:
      description: Retrieve random verse
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get Dailly verses
      tags:
      - MemoryVerse
  /memoryverse/dashboard:
    get:
      description: Retrieve user's memory verse, notes, and history
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user dashboard data
      tags:
      - MemoryVerse
  /memoryverse/get-favourite-verses:
    get:
      description: Retrieve all verses that the user has marked as favourites
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user's favourite verses
      tags:
      - MemoryVerse
  /memoryverse/save-note:
    post:
      description: Save user verse note
      parameters:
      - description: Save user note request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/memoryverse.SaveUserNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user's Verses Note
      tags:
      - MemoryVerse
  /memoryverse/toggle-favourite-verse:
    patch:
      consumes:
      - application/json
      description: Toggle favourite verse status for logged-in user
      parameters:
      - description: Verse ID to toggle
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/memoryverse.AddToFavouriteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Add or remove a verse from favourites
      tags:
      - MemoryVerse
  /memoryverse/unsubscribe:
    get:
      description: Toggle user subscription status for verse delivery
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Unsubscribe or re-subscribe user
      tags:
      - MemoryVerse
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
